// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/teachingVideo/getTeachingVideoList": {
            "post": {
                "tags": [
                    "SysTeachingVideo"
                ],
                "summary": "查询视频",
                "responses": {}
            }
        },
        "/teachingVideo/upload": {
            "post": {
                "tags": [
                    "AddTeachingVideoApi"
                ],
                "summary": "新增SysTeachingVideo",
                "responses": {
                    "200": {
                        "description": "新增成功"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "swagger API",
	Description:      "暂无",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
