basePath: /
info:
  contact: {}
  description: 暂无
  title: swagger API
  version: 1.1.1
paths:
  /teachingVideo/upload:
    post:
      responses:
        "200":
          description: 新增成功
      summary: 新增SysTeachingVideo
      tags:
      - AddTeachingVideoApi
swagger: "2.0"
